controller_manager:
  ros__parameters:
    update_rate: 20 # Hz
    rover_base_control:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

rover_base_control:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: ["Rueda_del_iz_link_joint", "Rueda_cen_iz_link_joint", "Rueda_tras_iz_link_joint"]
    right_wheel_names: ["Rueda_del_der_link_joint", "Rueda_cen_der_link_joint", "Rueda_tras_der_link_joint"]
    wheel_separation: 2.0
    wheel_radius: 0.25
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    base_frame_id: base_footprint
    # odom tf will be published by direct laser odometry
    enable_odom_tf: true
    # Publish limited velocity
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0

/**/scara_controller:
  ros__parameters:
    joints:
      - Union_base_L1_link_joint
      - Union_eje_L2_link_joint
      - Brazo_L3_link_joint
      - Base_pinza_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
  
/**/gripper_controller:
  ros__parameters:
    joints:
      - Dedo_der_link_joint
      - Dedo_iz_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true